/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UgKVRficoM7
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { ModeToggle } from "../ModeToggle";

export function Navbar() {
  return (
    <header className="backdrop-blur-2xl flex w-full shrink-0 items-center py-2 md:py-4 px-4 md:px-6 border-b">
      <Link
        href="/"
        className="mr-1 md:mr-6 flex items-center"
        prefetch={false}
      >
        <MountainIcon className="hidden lg:flex h-6 w-6" />
        <span className="text-lg font-bold">SLNP</span>
      </Link>
      <nav className="flex items-center gap-2 md:gap-6">
        <Link
          href="/companies"
          className="text-sm font-medium hover:underline underline-offset-4"
          prefetch={false}
        >
          Companies
        </Link>
        <Link
          href="/invoices"
          className="text-sm font-medium hover:underline underline-offset-4"
          prefetch={false}
        >
          Invoices
        </Link>
        <Link
          href="#"
          className="text-sm font-medium hover:underline underline-offset-4"
          prefetch={false}
        >
          Items
        </Link>
      </nav>
      <div className="ml-auto flex justify-center gap-2">
        <ModeToggle />
        <Link href={"/invoices/new"}>
          <Button className="text-xs md:text-sm p-1 md:p-2">+ Invoice</Button>
        </Link>
      </div>
    </header>
  );
}

function MountainIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}

function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
